### ISSUE TITLE
question: empty variables expansion

### ISSUE THREAD

**Issue by avoidik** [ncopa/su-exec#12]
BLAH is undefined
```
#!/usr/bin/env bash
set -x
su-exec do-the "${BLAH}" with-params
```
expands to `su-exec do-the '' with-params`
```
#!/usr/bin/env sh
set -x
su-exec do-the "${BLAH}" with-params
```
expands to `su-exec do-the  with-params`

meanwhile
```
#!/usr/bin/env bash
set -x
su-exec do-the ${BLAH} with-params
```
expands to `su-exec do-the with-params` properly, but this is unsecure

As you may see in **bash** an empty variable has been surrounded by the single quotes and empty for **sh**.

Is that proper behavior for empty variables expansion?

**Comment by ncopa** [comment]
This works as intended, but the difference is only how bash and sh implements the output of `set -x`. bash prints the `''` to indicate that there is an empty string arg, sh will not print it, but it is there.

Here is a test app in C to demonstrate:
````
ncopa-desktop:~/test$ cat args.c 
#include <stdio.h>

int main(int argc, char *argv[])
{
	int i;
	for (i=0; i<argc; i++)
		printf("arg[%d]=%s\n", i, argv[i]);
	return 0;
}
ncopa-desktop:~/test$ cat test.bash
#!/usr/bin/env bash
set -x
./args "${BLAH}" with-params
ncopa-desktop:~/test$ ./test.bash
+ ./args '' with-params
arg[0]=./args
arg[1]=
arg[2]=with-params
ncopa-desktop:~/test$ cat test.sh
#!/usr/bin/env sh
set -x
./args "${BLAH}" with-params
ncopa-desktop:~/test$ ./test.sh 
+ ./args  with-params
arg[0]=./args
arg[1]=
arg[2]=with-params
````

With unquoted variable in bash it gives same result:

````
ncopa-desktop:~/test$ cat test2.bash 
#!/usr/bin/env bash
set -x
./args ${BLAH} with-params
ncopa-desktop:~/test$ ./test2.bash
+ ./args with-params
arg[0]=./args
arg[1]=with-params
````

As you see without the quotes `${BLAH}` the arg will excluded as no arg. With the quotes `"${BLAH}"` the arg will be passed over, but as empty string. The only difference is that with bash `set -x` will print the `''` to indicate this.

This has not really anything to with su-exec.

**Comment by avoidik** [comment]
may I re-open this with explanation why this might be related to a su-exec
https://github.com/openfrontier/docker-gerrit/issues/71
