### ISSUE TITLE
'cd' command is not working

### ISSUE THREAD

**Issue by bwieckow** [ncopa/su-exec#28]
Once I execute 
`su-exec ubuntu cd /home`
I got following output:
`su-exec: cd: No such file or directory`

On the other hand, once I execute `su-exec ubuntu ls -l /home` the command is working properly.
Output:
`total 0`

Generally, it is only `cd` not working for me. Thus, I find it as a bug.

**Comment by tianon** [comment]
This would be because `cd` isn't a command, it's a shell built-in.

**Comment by ncopa** [comment]
You need a binary to execute, and as @tianon mentioned, the binary is shell (`sh`).
`su-exec ubuntu sh -c "cd /home"`
